version: '3.4'
services:
  db:
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - scheduler-network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - scheduler-network
  api:
    image: murilofelpeto/scheduler-api
    build: ./
    ports:
      - "8080:8080"
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    networks:
      - scheduler-network
networks:
  scheduler-network:
    driver: bridge
volumes:
  database-data: